---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-pod
  labels:
    app: exporter-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-pod
  template:
    metadata:
      labels:
        app: exporter-pod
    spec:
      containers:
        - name: account-exporter
          image: "eu.gcr.io/p2pcloud-327512/account-exporter:latest"
          ports:
             - containerPort: 2000
        - name: staking-exporter
          image: "eu.gcr.io/p2pcloud-327512/staking-exporter:latest"
          ports:
             - containerPort: 2000
        
